### ISSUE TITLE
one_step_gp.py failing with zipfile.BadZipFile: Bad magic number for file header

### ISSUE THREAD

**Issue by kunalghosh** [kunalghosh/Multi_Fidelity_Prediction_GP#5]
> (base) ➜  debug git:(testing_runs) ✗ python ../one_step_gp.py input.dat
/Users/ghoshk1/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:30: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  method='lar', copy_X=True, eps=np.finfo(np.float).eps,
/Users/ghoshk1/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:167: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  method='lar', copy_X=True, eps=np.finfo(np.float).eps,
/Users/ghoshk1/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:284: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps, copy_Gram=True, verbose=0,
/Users/ghoshk1/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:862: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps, copy_X=True, fit_path=True,
/Users/ghoshk1/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:1101: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps, copy_X=True, fit_path=True,
/Users/ghoshk1/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:1127: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps, positive=False):
/Users/ghoshk1/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:1362: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  max_n_alphas=1000, n_jobs=None, eps=np.finfo(np.float).eps,
/Users/ghoshk1/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:1602: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  max_n_alphas=1000, n_jobs=None, eps=np.finfo(np.float).eps,
/Users/ghoshk1/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:1738: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps, copy_X=True, positive=False):
/Users/ghoshk1/anaconda3/lib/python3.7/site-packages/sklearn/decomposition/online_lda.py:29: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  EPS = np.finfo(np.float).eps
/Users/ghoshk1/anaconda3/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
{'fn_name': 'rnd2', 'out_name': 'test-A-1k', 'dataset': 'AA', 'dataset_size': '44004', 'test_set_size': '10000', 'rnd_size': '2.0', 'K_high': '100', 'random_seed': '1234', 'mbtr_red': 'False', 'preprocess': 'none', 'kernel_type': 'constRBF', 'length': '700', 'const': '20', 'bound': '1e2', 'n_opt': '0', 'save_load_flag': 'save', 'save_load_split_flag': 'False', 'restart_flag': 'False', 'num_itr': '4', 'pre_idxs_0': '1000', 'pre_idxs_1': '1000', 'pre_idxs_2': '2000', 'pre_idxs_3': '4000', 'pre_idxs_4': '8000', 'mbtr_path': '../../../../MFGP_data/AA/mbtr_k2.npz', 'json_path': '../../../../MFGP_data/AA/HOMO.txt', 'loadidxs_path': '../../../../MFGP_data/AA_derived/10K_dataset_load_high/10Kloadhigh2_0_idxs.npz', 'loadsplitidxs_path': '../../../../MFGP_data/AA_derived/10K_dataset_load_high/10Kdataset_dataset_split_idxs.npz'}
rnd2
rnd2
test-A-1k
4
100
AA
44004
10000
2.0
False
none
save
False
700
20
1e2
0
constRBF
False
1234
1000
1000
2000
4000
8000
../../../../MFGP_data/AA/mbtr_k2.npz
../../../../MFGP_data/AA/HOMO.txt
../../../../MFGP_data/AA_derived/10K_dataset_load_high/10Kloadhigh2_0_idxs.npz
../../../../MFGP_data/AA_derived/10K_dataset_load_high/10Kdataset_dataset_split_idxs.npz
Loaded data.
1 1000
/Users/ghoshk1/anaconda3/lib/python3.7/site-packages/sklearn/gaussian_process/gpr.py:346: UserWarning: Predicted variances smaller than 0. Setting those variances to 0.
  warnings.warn("Predicted variances smaller than 0. "
2 2000
Traceback (most recent call last):
  File "../one_step_gp.py", line 302, in <module>
    main()
  File "../one_step_gp.py", line 243, in main
    pred_idxs = data['prediction_idxs']
  File "/Users/ghoshk1/anaconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 249, in __getitem__
    bytes = self.zip.open(key)
  File "/Users/ghoshk1/anaconda3/lib/python3.7/zipfile.py", line 1491, in open
    raise BadZipFile("Bad magic number for file header")
zipfile.BadZipFile: Bad magic number for file header

**Comment by kunalghosh** [comment]
This was happening, because the `data['prediction_idxs']` had already loaded the data and the next time around there is no data left for it to load from the npz file.
